version: 2.0

jobs:
  setup_project:
    docker:
    - image: circleci/python:3.7.2
    steps:
    - checkout
    - run:
        name: Install Python dependencies in a venv
        command: |
          python3 -m venv env
          source env/bin/activate
          python -m pip install -r requirements.txt
    - persist_to_workspace:
        root: .
        paths:
          - env/*
          - .
  chrome-tests:
    docker:
    - image: circleci/python:3.7.2
    - image: selenium/standalone-chrome:3.141.59-iron
    steps:
    - attach_workspace:
        at: .
    - run:
        name: run tests chrome
        command: |
          source env/bin/activate
          export BROWSER="chrome"
          pytest -v Tests --html=test-reports/report.html
          # ./run-tests.sh -b chrome -p Tests
    - store_artifacts:
          path: test-reports
          destination: test-reports
  firefox-tests:
    docker:
    - image: circleci/python:3.7.2
    - image: selenium/standalone-firefox:3.141.59-iron
    steps:
    - attach_workspace:
        at: .
    - run:
        name: run tests firefox
        command: |
          source env/bin/activate
          export BROWSER="firefox"
          pytest -v Tests --html=test-reports/report.html
          # ./run-tests.sh -b firefox -p Tests
    - store_artifacts:
          path: test-reports
          destination: test-reports
workflows:
  version: 2
  run_e2e_tests:
    jobs:
      - setup_project
      - chrome-tests:
          requires:
            - setup_project
      - firefox-tests:
          requires:
            - setup_project
